'use client';
import { RecoilRoot } from 'recoil'
import Providers from './components/Providers'
import './globals.css'
import { Inter } from 'next/font/google'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Instagram 2.0 Build',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className={inter.className}>
        <Providers>
          <RecoilRoot>
          {children}
          </RecoilRoot>
        </Providers> 
      </body>
    </html>
  )
}
